export { synthesize, pickDecorationFrame } from "./synthesize.js";
export type { SynthPlan, SynthResult } from "./synthesize.js";
export { buildGrammarSpec } from "./grammar.js";
export type { GrammarSpec, ArchetypeSkeleton, ArchetypeZone } from "./grammar.js";
export { synthesizeFromGrammar, archetypeSchema, describeRoles } from "./synth-engine.js";
export type { ContentPlan, Asset } from "./synth-engine.js";
export { evaluateSlide } from "./evaluate.js";
export type { QualityScores, QualityVerdict } from "./evaluate.js";
export { synthDecoration, chooseDecoration, pickDecoration } from "./decoration.js";
export type { DecoFrag } from "./decoration.js";
export { makeStructures, STRUCTURE_FOR_ARCHETYPE, STRUCTURE_SCHEMA } from "./structures.js";
export type { Structure, StructName, Region } from "./structures.js";
export { buildLayoutBank, signature } from "./layout-bank.js";
export type { LayoutSig } from "./layout-bank.js";
export { BLOCK_SCHEMA, blockCount, blockMatches } from "./blocks.js";
export type { BlockKind } from "./blocks.js";
export { selectLayout, scoreLayout, availableKinds } from "./select.js";
export type { PlanBlock } from "./select.js";
export { planFromBlock } from "./render-block.js";
export type { BlockPlacement } from "./render-block.js";
